// Code generated by qtc from "multipart_form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line multipart_form.qtpl:1
package example_templates

//line multipart_form.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line multipart_form.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line multipart_form.qtpl:1
func StreamMulipartForm(qw422016 *qt422016.Writer, link, content string) {
//line multipart_form.qtpl:1
	qw422016.N().S(`
<div class="auth">
    <form enctype="multipart/form-data" action="`)
//line multipart_form.qtpl:3
	qw422016.E().S(link)
//line multipart_form.qtpl:3
	qw422016.N().S(`" method="post">
        `)
//line multipart_form.qtpl:4
	qw422016.N().S(content)
//line multipart_form.qtpl:4
	qw422016.N().S(`
        <input type="submit" class="btn btn-primary" value="Save">
    </form>
</div>
`)
//line multipart_form.qtpl:8
}

//line multipart_form.qtpl:8
func WriteMulipartForm(qq422016 qtio422016.Writer, link, content string) {
//line multipart_form.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line multipart_form.qtpl:8
	StreamMulipartForm(qw422016, link, content)
//line multipart_form.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line multipart_form.qtpl:8
}

//line multipart_form.qtpl:8
func MulipartForm(link, content string) string {
//line multipart_form.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line multipart_form.qtpl:8
	WriteMulipartForm(qb422016, link, content)
//line multipart_form.qtpl:8
	qs422016 := string(qb422016.B)
//line multipart_form.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line multipart_form.qtpl:8
	return qs422016
//line multipart_form.qtpl:8
}
