// Code generated by qtc from "form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line form.qtpl:1
package twftemplates

//line form.qtpl:1
import "github.com/tochk/twf/datastruct"

//line form.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line form.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line form.qtpl:3
func StreamForm(qw422016 *qt422016.Writer, link, content string) {
//line form.qtpl:3
	qw422016.N().S(`
<div class="auth">
    <form action="`)
//line form.qtpl:5
	qw422016.E().S(link)
//line form.qtpl:5
	qw422016.N().S(`" method="post">
        `)
//line form.qtpl:6
	qw422016.N().S(content)
//line form.qtpl:6
	qw422016.N().S(`
        <input type="submit" class="btn btn-primary" value="Save">
    </form>
</div>
`)
//line form.qtpl:10
}

//line form.qtpl:10
func WriteForm(qq422016 qtio422016.Writer, link, content string) {
//line form.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line form.qtpl:10
	StreamForm(qw422016, link, content)
//line form.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line form.qtpl:10
}

//line form.qtpl:10
func Form(link, content string) string {
//line form.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line form.qtpl:10
	WriteForm(qb422016, link, content)
//line form.qtpl:10
	qs422016 := string(qb422016.B)
//line form.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line form.qtpl:10
	return qs422016
//line form.qtpl:10
}

//line form.qtpl:13
func StreamFormItem(qw422016 *qt422016.Writer, field datastruct.Field) {
//line form.qtpl:13
	qw422016.N().S(`
<div class="form-group">
    <label for="`)
//line form.qtpl:15
	qw422016.E().S(field.Name)
//line form.qtpl:15
	qw422016.N().S(`">`)
//line form.qtpl:15
	qw422016.E().S(field.Title)
//line form.qtpl:15
	qw422016.N().S(`</label>
    <input type="`)
//line form.qtpl:16
	qw422016.E().S(field.Type)
//line form.qtpl:16
	qw422016.N().S(`" `)
//line form.qtpl:16
	if field.Required {
//line form.qtpl:16
		qw422016.N().S(` required `)
//line form.qtpl:16
	}
//line form.qtpl:16
	qw422016.N().S(` name="`)
//line form.qtpl:16
	qw422016.E().S(field.Name)
//line form.qtpl:16
	qw422016.N().S(`" class="form-control"
           id="`)
//line form.qtpl:17
	qw422016.E().S(field.Name)
//line form.qtpl:17
	qw422016.N().S(`" placeholder="Enter `)
//line form.qtpl:17
	qw422016.E().S(field.Title)
//line form.qtpl:17
	qw422016.N().S(`"  value="`)
//line form.qtpl:17
	qw422016.E().V(field.Value)
//line form.qtpl:17
	qw422016.N().S(`">
</div>
`)
//line form.qtpl:19
}

//line form.qtpl:19
func WriteFormItem(qq422016 qtio422016.Writer, field datastruct.Field) {
//line form.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line form.qtpl:19
	StreamFormItem(qw422016, field)
//line form.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line form.qtpl:19
}

//line form.qtpl:19
func FormItem(field datastruct.Field) string {
//line form.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line form.qtpl:19
	WriteFormItem(qb422016, field)
//line form.qtpl:19
	qs422016 := string(qb422016.B)
//line form.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line form.qtpl:19
	return qs422016
//line form.qtpl:19
}

//line form.qtpl:21
func StreamFormItemTextarea(qw422016 *qt422016.Writer, field datastruct.Field) {
//line form.qtpl:21
	qw422016.N().S(`
<div class="form-group">
    <label for="`)
//line form.qtpl:23
	qw422016.E().S(field.Name)
//line form.qtpl:23
	qw422016.N().S(`">`)
//line form.qtpl:23
	qw422016.E().S(field.Title)
//line form.qtpl:23
	qw422016.N().S(`</label>
    <textarea name="`)
//line form.qtpl:24
	qw422016.E().S(field.Name)
//line form.qtpl:24
	qw422016.N().S(`" rows="10" class="form-control" id="`)
//line form.qtpl:24
	qw422016.E().S(field.Name)
//line form.qtpl:24
	qw422016.N().S(`" placeholder="Enter `)
//line form.qtpl:24
	qw422016.E().S(field.Title)
//line form.qtpl:24
	qw422016.N().S(`">`)
//line form.qtpl:24
	qw422016.E().V(field.Value)
//line form.qtpl:24
	qw422016.N().S(`</textarea>
</div>
`)
//line form.qtpl:26
}

//line form.qtpl:26
func WriteFormItemTextarea(qq422016 qtio422016.Writer, field datastruct.Field) {
//line form.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line form.qtpl:26
	StreamFormItemTextarea(qw422016, field)
//line form.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line form.qtpl:26
}

//line form.qtpl:26
func FormItemTextarea(field datastruct.Field) string {
//line form.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line form.qtpl:26
	WriteFormItemTextarea(qb422016, field)
//line form.qtpl:26
	qs422016 := string(qb422016.B)
//line form.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line form.qtpl:26
	return qs422016
//line form.qtpl:26
}

//line form.qtpl:28
func StreamFormItemSelect(qw422016 *qt422016.Writer, field datastruct.Field, kvs []datastruct.FkKV, selectedID interface{}) {
//line form.qtpl:28
	qw422016.N().S(`
<div class="form-group">
    <label for="`)
//line form.qtpl:30
	qw422016.E().S(field.Name)
//line form.qtpl:30
	qw422016.N().S(`">`)
//line form.qtpl:30
	qw422016.E().S(field.Title)
//line form.qtpl:30
	qw422016.N().S(`</label>
    <select class="form-control" id="`)
//line form.qtpl:31
	qw422016.E().S(field.Name)
//line form.qtpl:31
	qw422016.N().S(`" name="`)
//line form.qtpl:31
	qw422016.E().S(field.Name)
//line form.qtpl:31
	qw422016.N().S(`">
            `)
//line form.qtpl:32
	for _, e := range kvs {
//line form.qtpl:32
		qw422016.N().S(`
            <option `)
//line form.qtpl:33
		if selectedID != nil {
//line form.qtpl:33
			qw422016.N().S(` `)
//line form.qtpl:33
			if selectedID == e.ID {
//line form.qtpl:33
				qw422016.N().S(` selected `)
//line form.qtpl:33
			}
//line form.qtpl:33
			qw422016.N().S(` `)
//line form.qtpl:33
		}
//line form.qtpl:33
		qw422016.N().S(` value="`)
//line form.qtpl:33
		qw422016.E().V(e.ID)
//line form.qtpl:33
		qw422016.N().S(`">`)
//line form.qtpl:33
		qw422016.E().V(e.Name)
//line form.qtpl:33
		qw422016.N().S(`</option>
            `)
//line form.qtpl:34
	}
//line form.qtpl:34
	qw422016.N().S(`
    </select>
</div>
`)
//line form.qtpl:37
}

//line form.qtpl:37
func WriteFormItemSelect(qq422016 qtio422016.Writer, field datastruct.Field, kvs []datastruct.FkKV, selectedID interface{}) {
//line form.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line form.qtpl:37
	StreamFormItemSelect(qw422016, field, kvs, selectedID)
//line form.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line form.qtpl:37
}

//line form.qtpl:37
func FormItemSelect(field datastruct.Field, kvs []datastruct.FkKV, selectedID interface{}) string {
//line form.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line form.qtpl:37
	WriteFormItemSelect(qb422016, field, kvs, selectedID)
//line form.qtpl:37
	qs422016 := string(qb422016.B)
//line form.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line form.qtpl:37
	return qs422016
//line form.qtpl:37
}

//line form.qtpl:39
func StreamFormItemCheckbox(qw422016 *qt422016.Writer, field datastruct.Field) {
//line form.qtpl:39
	qw422016.N().S(`
<div class="form-group">
    <label for="`)
//line form.qtpl:41
	qw422016.E().S(field.Name)
//line form.qtpl:41
	qw422016.N().S(`">`)
//line form.qtpl:41
	qw422016.E().S(field.Title)
//line form.qtpl:41
	qw422016.N().S(`</label>
    <input type="checkbox" name="`)
//line form.qtpl:42
	qw422016.E().S(field.Name)
//line form.qtpl:42
	qw422016.N().S(`" `)
//line form.qtpl:42
	if field.Value == "true" {
//line form.qtpl:42
		qw422016.N().S(` checked `)
//line form.qtpl:42
	}
//line form.qtpl:42
	qw422016.N().S(`  value="on" class="form-control" id="`)
//line form.qtpl:42
	qw422016.E().S(field.Name)
//line form.qtpl:42
	qw422016.N().S(`" placeholder="Enter `)
//line form.qtpl:42
	qw422016.E().S(field.Title)
//line form.qtpl:42
	qw422016.N().S(`">
</div>
`)
//line form.qtpl:44
}

//line form.qtpl:44
func WriteFormItemCheckbox(qq422016 qtio422016.Writer, field datastruct.Field) {
//line form.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line form.qtpl:44
	StreamFormItemCheckbox(qw422016, field)
//line form.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line form.qtpl:44
}

//line form.qtpl:44
func FormItemCheckbox(field datastruct.Field) string {
//line form.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line form.qtpl:44
	WriteFormItemCheckbox(qb422016, field)
//line form.qtpl:44
	qs422016 := string(qb422016.B)
//line form.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line form.qtpl:44
	return qs422016
//line form.qtpl:44
}
