// Code generated by qtc from "head.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line head.qtpl:1
package twftemplates

//line head.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line head.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line head.qtpl:1
func StreamHead(qw422016 *qt422016.Writer, title string) {
//line head.qtpl:1
	qw422016.N().S(`
<html lang="en">
<head>
    <title>`)
//line head.qtpl:4
	qw422016.E().S(title)
//line head.qtpl:4
	qw422016.N().S(`</title>
    <link rel="stylesheet"
          href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css"
          integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link rel="stylesheet" href="/web/static/template.css">
    <style>
        .auth {
            width: 400px;
            margin: 50px auto 0;
        }

        .form {
            width: 500px;
            margin: 50px auto 0;
        }

        .error {
            width: 800px;
            margin: 50px auto 0;
        }

        tr:hover {
            background-color: lightblue !important;
        }
    </style>
</head>
<body>
`)
//line head.qtpl:31
}

//line head.qtpl:31
func WriteHead(qq422016 qtio422016.Writer, title string) {
//line head.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line head.qtpl:31
	StreamHead(qw422016, title)
//line head.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line head.qtpl:31
}

//line head.qtpl:31
func Head(title string) string {
//line head.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line head.qtpl:31
	WriteHead(qb422016, title)
//line head.qtpl:31
	qs422016 := string(qb422016.B)
//line head.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line head.qtpl:31
	return qs422016
//line head.qtpl:31
}
