// Code generated by qtc from "item.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line item.qtpl:1
package twftemplates

//line item.qtpl:1
import "github.com/tochk/twf/datastruct"

//line item.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line item.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line item.qtpl:3
func StreamItemList(qw422016 *qt422016.Writer, fields []datastruct.Field, content string) {
//line item.qtpl:3
	qw422016.N().S(`
<table class="table">
    <thead class="thead-dark">
    <tr>
        `)
//line item.qtpl:7
	for _, field := range fields {
//line item.qtpl:7
		qw422016.N().S(`
        <th>`)
//line item.qtpl:8
		qw422016.E().S(field.Title)
//line item.qtpl:8
		qw422016.N().S(`</th>
        `)
//line item.qtpl:9
	}
//line item.qtpl:9
	qw422016.N().S(`
    </tr>
    </thead>
    <tbody>
        `)
//line item.qtpl:13
	qw422016.N().S(content)
//line item.qtpl:13
	qw422016.N().S(`
    </tbody>
</table>
`)
//line item.qtpl:16
}

//line item.qtpl:16
func WriteItemList(qq422016 qtio422016.Writer, fields []datastruct.Field, content string) {
//line item.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line item.qtpl:16
	StreamItemList(qw422016, fields, content)
//line item.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line item.qtpl:16
}

//line item.qtpl:16
func ItemList(fields []datastruct.Field, content string) string {
//line item.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line item.qtpl:16
	WriteItemList(qb422016, fields, content)
//line item.qtpl:16
	qs422016 := string(qb422016.B)
//line item.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line item.qtpl:16
	return qs422016
//line item.qtpl:16
}

//line item.qtpl:18
func StreamItem(qw422016 *qt422016.Writer, values []interface{}) {
//line item.qtpl:18
	qw422016.N().S(`
<tr>
`)
//line item.qtpl:20
	for _, value := range values {
//line item.qtpl:20
		qw422016.N().S(`
    <td>`)
//line item.qtpl:21
		qw422016.N().V(value)
//line item.qtpl:21
		qw422016.N().S(`</td>
`)
//line item.qtpl:22
	}
//line item.qtpl:22
	qw422016.N().S(`
</tr>
`)
//line item.qtpl:24
}

//line item.qtpl:24
func WriteItem(qq422016 qtio422016.Writer, values []interface{}) {
//line item.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line item.qtpl:24
	StreamItem(qw422016, values)
//line item.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line item.qtpl:24
}

//line item.qtpl:24
func Item(values []interface{}) string {
//line item.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line item.qtpl:24
	WriteItem(qb422016, values)
//line item.qtpl:24
	qs422016 := string(qb422016.B)
//line item.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line item.qtpl:24
	return qs422016
//line item.qtpl:24
}
